volumes:
  sonarqube_data:
  sonarqube_extensions:

networks:
  monitor-net:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tenda-atacado-cupom-service
    ports:
      - "8084:8084"
    environment:
      - ADMIN_SERVICE_PORT=8084
      - TZ=America/Sao_Paulo
    networks:
      - monitor-net
    depends_on:
      - sonarqube
    restart: unless-stopped

  sonarqube:
    image: sonarqube:8.9-community
    container_name: tenda-atacado-cupom-sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - monitor-net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    restart: unless-stopped